### ISSUE TITLE
升级到1.12.3之后，一直出现getMsg发生，之前用的1.11.0版本没出现过

### ISSUE THREAD

**Issue by MooMXiZ1** [takayama-lily/oicq#118]
![image](https://user-images.githubusercontent.com/41711944/103262848-0c6ef680-49e1-11eb-9a10-0caa6dc06b12.png)

**Comment by takayama-lily** [comment]
能否提供前后更多一点的日志

**Comment by MooMXiZ1** [comment]
![image](https://user-images.githubusercontent.com/41711944/103264120-bc922e80-49e4-11eb-9ff6-5118e3e50cee.png)

**Comment by MooMXiZ1** [comment]
[2020-12-29T14:46:13.697] [INFO] [BOT:1684250818] - connecting to msfwifi.3g.qq.
com:8080
[2020-12-29T14:46:13.742] [INFO] [BOT:1684250818] - 113.96.13.87:8080 connected
[2020-12-29T14:46:13.916] [INFO] [BOT:1684250818] - 113.96.13.87:8080 closed
[2020-12-29T14:46:18.643] [DEBUG] [BOT:1684250818] - getMsg发生错误。
[2020-12-29T14:46:18.648] [DEBUG] [BOT:1684250818] - TimeoutError
    at Timeout._onTimeout (C:\Users\gaozhe\Desktop\SJ_onebot\node_modules\oicq\c
lient.js:221:28)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[2020-12-29T14:46:18.767] [ERROR] [BOT:1684250818] - register失败。
[2020-12-29T14:46:18.771] [WARN] [BOT:1684250818] - 5秒后重新连接。
[2020-12-29T14:46:23.789] [INFO] [BOT:1684250818] - connecting to msfwifi.3g.qq.
com:8080
[2020-12-29T14:46:23.839] [INFO] [BOT:1684250818] - 113.96.13.87:8080 connected
[2020-12-29T14:46:24.464] [INFO] [BOT:1684250818] - Welcome, Olivia ! 开始初始化
资源...
[2020-12-29T14:46:24.529] [DEBUG] [BOT:1684250818] - Error: unknown jce type: 14

    at readBody (C:\Users\gaozhe\Desktop\SJ_onebot\node_modules\jce\jce.js:112:1
9)
    at readElement (C:\Users\gaozhe\Desktop\SJ_onebot\node_modules\jce\jce.js:20
2:17)
    at Object.decode (C:\Users\gaozhe\Desktop\SJ_onebot\node_modules\jce\jce.js:
370:30)
    at Object.decodeWrapper (C:\Users\gaozhe\Desktop\SJ_onebot\node_modules\oicq
\lib\jce.js:20:25)
    at AndroidClient.onPushReq (C:\Users\gaozhe\Desktop\SJ_onebot\node_modules\o
icq\lib\core.js:19:24)
    at AndroidClient.parseIncomingPacket (C:\Users\gaozhe\Desktop\SJ_onebot\node
_modules\oicq\lib\core.js:293:25)
    at AndroidClient.<anonymous> (C:\Users\gaozhe\Desktop\SJ_onebot\node_modules
\oicq\client.js:146:50)
    at AndroidClient.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:558:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
[2020-12-29T14:46:27.713] [INFO] [BOT:1684250818] - 加载了1832个好友，52个群。
[2020-12-29T14:46:27.718] [INFO] [BOT:1684250818] - 初始化完毕，开始处理消息。

**Comment by takayama-lily** [comment]
这个日志看上去是第一次连接失败了，然后重连后没问题。

相比之下我更在意上面的连续3个getMsg超时之前发生了什么。。

**Comment by MooMXiZ1** [comment]
cron_config_interval: 10000,
  version: '1.12.3.1',
  redis_config: { host: '192.168.0.4', port: '6379', index: 1 }
}
[2020-12-29T14:46:11.822] [INFO] [BOT:1684250818] - 开启http服务器成功，监听0.0.
0.0:5004
[2020-12-29T14:46:12.326] [INFO] [BOT:1684250818] - connecting to msfwifi.3g.qq.
com:8080
[2020-12-29T14:46:12.408] [INFO] [BOT:1684250818] - 113.96.13.87:8080 connected
[2020-12-29T14:46:13.354] [INFO] [BOT:1684250818] - Welcome, Olivia ! 开始初始化
资源...
[2020-12-29T14:46:13.635] [INFO] [BOT:1684250818] - 113.96.13.87:8080 closed
[2020-12-29T14:46:13.697] [INFO] [BOT:1684250818] - connecting to msfwifi.3g.qq.
com:8080
[2020-12-29T14:46:13.742] [INFO] [BOT:1684250818] - 113.96.13.87:8080 connected
[2020-12-29T14:46:13.916] [INFO] [BOT:1684250818] - 113.96.13.87:8080 closed
[2020-12-29T14:46:18.643] [DEBUG] [BOT:1684250818] - getMsg发生错误。
[2020-12-29T14:46:18.648] [DEBUG] [BOT:1684250818] - TimeoutError

**Comment by MooMXiZ1** [comment]
最上面是已加载配置文件提示信息，然后依次connected两次closed之后就出现getMsg错误提示了

**Comment by takayama-lily** [comment]
恩，是ip不稳定导致的
临时解决方法是手动设定hosts更换ip
https://site.ip138.com/msfwifi.3g.qq.com/ 这里面的ip都可以使用

**Comment by takayama-lily** [comment]
另外，如果自动重试能连上，而不是一直连不上，就不用更换了

**Comment by MooMXiZ1** [comment]
好的，我先试试，谢谢
