### ISSUE TITLE
消息报文有部分不符合OneBot的规范

### ISSUE THREAD

**Issue by moebuii** [takayama-lily/oicq#139]
也许比较偏，因为这个问题是node-onebot那边，但是这个bug算是oicq部分的，所以就反馈到这里了

因为原先的bot是用nonebot写的，也算比较旧了，所以现在在使用nonebot2重写，但是oicq在推送消息报文到nonebot2之后，nonebot2就抛出了下列错误
```
 03-05` 07:13:43 [DEBUG] nonebot | CQHTTP | Event Parser Error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/opt/homebrew/lib/python3.9/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/opt/homebrew/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 313, in handle_message
    event = model.parse_obj(message)
  File "/opt/homebrew/lib/python3.9/site-packages/pydantic/main.py", line 520, in parse_obj
    return cls(**obj)
  File "/opt/homebrew/lib/python3.9/site-packages/pydantic/main.py", line 362, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for PrivateMessageEvent
message_id
  value is not a valid integer (type=type_error.integer)
font
  value is not a valid integer (type=type_error.integer)
03-05 07:13:43 [DEBUG] nonebot | CQHTTP | Event Parser Error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/opt/homebrew/lib/python3.9/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/opt/homebrew/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 313, in handle_message
    event = model.parse_obj(message)
  File "/opt/homebrew/lib/python3.9/site-packages/pydantic/main.py", line 520, in parse_obj
    return cls(**obj)
  File "/opt/homebrew/lib/python3.9/site-packages/pydantic/main.py", line 362, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for MessageEvent
message_id
  value is not a valid integer (type=type_error.integer)
font
  value is not a valid integer (type=type_error.integer)
03-05 07:13:43 [INFO] nonebot | CQHTTP 2422506249 | [message]: {'time': 1614899623, 'self_id': 2422506249, 'post_type': 'message', 'user_id': 996005984, 'sub_type': 'friend', 'sender': {'user_id': 996005984, 'nickname': 'くろ兎', 'sex': 'male', 'age': 0, 'area': 'unknown', 'remark': 'くろ兎'}, 'message': 'test', 'raw_message': 'test', 'font': 'Helvetica', 'auto_reply': False, 'message_type': 'private', 'message_id': 'O13YYAAAEExx0fhjYEFppw=='}
03-05 07:13:43 [ERROR] nonebot | Failed to handle event. Raw: {'self_id': 2422506249, 'time': 1614899623, 'post_type': 'message', 'message_type': 'private', 'sub_type': 'friend', 'message_id': 'O13YYAAAEExx0fhjYEFppw==', 'user_id': 996005984, 'message': 'test', 'raw_message': 'test', 'font': 'Helvetica', 'sender': {'user_id': 996005984, 'nickname': 'くろ兎', 'sex': 'male', 'age': 0, 'area': 'unknown', 'remark': 'くろ兎'}, 'auto_reply': False}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/opt/homebrew/lib/python3.9/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/opt/homebrew/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 325, in handle_message
    await handle_event(self, event)
  File "/opt/homebrew/lib/python3.9/site-packages/nonebot/message.py", line 221, in handle_event
    _, _ = TrieRule.get_value(bot, event, state)
  File "/opt/homebrew/lib/python3.9/site-packages/nonebot/rule.py", line 139, in get_value
    message = event.get_message()
  File "/opt/homebrew/lib/python3.9/site-packages/nonebot/adapters/cqhttp/event.py", line 44, in get_message
    raise ValueError("Event has no message!")
ValueError: Event has no message!
```
根据这个报错我去查了一下onebot的规范，发现即使是v10版本的规范，message_id和font也都是int32而非string，这个也许算是个bug

**Comment by takayama-lily** [comment]
要实现撤回等功能，使用字符串message_id是最好的办法，参考[消息id](https://github.com/takayama-lily/oicq/wiki/93.%E8%A7%A3%E6%9E%90%E6%B6%88%E6%81%AFID)
如果message_id使用一个无意义的整数，则必须内置数据库查询，会显著增加开销，还有重复的可能
对端大部分使用弱类型的语言，应该问题不大

font的话，本身就是string，暂时没有找到转换为int32的规则

**Comment by moebuii** [comment]
上报过去的报文中，font的话我个人觉得可以直接设置为0，通常情况下处理消息似乎并不需要这个（至少我看go-cqhttp处理这块也是直接设置成0）
message_id的话，针对nonebot2这种按照onebot规范规定数据类型的框架，我现在是把Buffer改成了以hex方式编码，然后再转为int上报至nonebot2

不过我这边转为int出了点问题，因为主用py的，不是很熟悉js，我在直接parseInt的时候出来的结果是浮点数。。。得先琢磨一下
