### ISSUE TITLE
探索服务器失败

### ISSUE THREAD

**Issue by TokisakiYuu** [takayama-lily/oicq#168]
* **你的操作系统**: win10

* **你的Node.js版本**: v12.14.0

* **使用的程序版本**: 1.17.2

* **使用的协议**: 手机(默认)

* [x] 我已确认过官方客户端不存在此问题，库的行为存在问题。

### 问题描述
探索服务器失败

### 详细日志
```bash
[2021-06-01T11:04:47.058] [MARK] [Android:1234567890] - ----------
[2021-06-01T11:04:47.062] [MARK] [Android:1234567890] - Package Version: oicq@1.17.2 (Released on 2021/5/24)
[2021-06-01T11:04:47.062] [MARK] [Android:1234567890] - View Changelogs：https://github.com/takayama-lily/oicq/releases
[2021-06-01T11:04:47.063] [MARK] [Android:1234567890] - ----------
[2021-06-01T11:04:47.067] [MARK] [Android:1234567890] - 正在探索可用服务器...
[2021-06-01T11:04:47.414] [WARN] [Android:1234567890] - 探索服务器失败: The "iterable" argument must be of type Iterable. Received type undefined
[2021-06-01T11:04:47.415] [MARK] [Android:1234567890] - connecting to msfwifi.3g.qq.com:8080
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string, Buffer, or Uint8Array. Received type number
    at chunkInvalid (_stream_readable.js:329:12)
    at readableAddChunk (_stream_readable.js:261:12)
    at Readable.push (_stream_readable.js:224:10)
    at next (internal/streams/from.js:34:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[ERROR] 11:04:47 TypeError: The "chunk" argument must be one of type string, Buffer, or Uint8Array. Received type number
```

**Comment by takayama-lily** [comment]
node12.14是不行的， 至少需要12.16

**Comment by TokisakiYuu** [comment]
> node12.14是不行的， 至少需要12.16

这版本要求着实有点高，考虑降nodejs版本吗？

**Comment by Cloud370** [comment]
> > node12.14是不行的， 至少需要12.16
> 
> 这版本要求着实有点高，考虑降nodejs版本吗？

12版本已经不高了 现在都普遍Node14了 就像你py3的项目考虑降py2

**Comment by takayama-lily** [comment]
主要12.16修复了一个重要的bug，正好有涉及到

**Comment by TokisakiYuu** [comment]
好的，谢谢你们的回复，不再讨论了
