### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Faker888888** [takayama-lily/oicq#295]
### Node.js Version

10.19.0

### Package Version

6.14.4

### Login Protocol

Android

### Bug Description

报错

### Log Details

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

**Comment by Cloud370** [comment]
node版本太低了
