### ISSUE TITLE
token 过期，以及一个retcode错误码

### ISSUE THREAD

**Issue by lc-cn** [takayama-lily/oicq#322]
### Node.js Version

16.9.0

### Package(oicq) Version

latest

### Login Protocol

iPad

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

登录频繁提示token过期，收到消息无任何相应

### Log Details (控制台日志，请提供包含前后一段时间内的)

[2022-03-13T17:40:50.571] [MARK] [iPad:210723495] - 49.7.253.214:8080 connected
[2022-03-13T17:40:50.859] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:40:51.180] [MARK] [iPad:210723495] - Welcome, 凉菜 ᴮᴼᵀ ! 正在加载资源...
[2022-03-13T17:40:51.223] [ERROR] [iPad:210723495] - Error: unsuccessful retcode: -10008
    at parseSso (E:\project\oitq\node_modules\oicq\lib\core\base-client.js:589:15)
    at Bot.packetListener (E:\project\oitq\node_modules\oicq\lib\core\base-client.js:629:27)
    at Network.emit (node:events:394:28)
    at Network.<anonymous> (E:\project\oitq\node_modules\oicq\lib\core\network.js:65:26)
    at Network.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Network.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  args: [ 2 ],
  event: 'internal.verbose'
}
[2022-03-13T17:40:51.302] [ERROR] [iPad:210723495] - Error: unsuccessful retcode: -10008
    at parseSso (E:\project\oitq\node_modules\oicq\lib\core\base-client.js:589:15)
    at Bot.packetListener (E:\project\oitq\node_modules\oicq\lib\core\base-client.js:629:27)
    at Network.emit (node:events:394:28)
    at Network.<anonymous> (E:\project\oitq\node_modules\oicq\lib\core\network.js:65:26)
    at Network.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Network.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  args: [ 2 ],
  event: 'internal.verbose'
}
[2022-03-13T17:40:51.303] [ERROR] [iPad:210723495] - Error: unsuccessful retcode: -10008
    at parseSso (E:\project\oitq\node_modules\oicq\lib\core\base-client.js:589:15)
    at Bot.packetListener (E:\project\oitq\node_modules\oicq\lib\core\base-client.js:629:27)
    at Network.emit (node:events:394:28)
    at Network.<anonymous> (E:\project\oitq\node_modules\oicq\lib\core\network.js:65:26)
    at Network.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Network.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  args: [ 2 ],
  event: 'internal.verbose'
}
[2022-03-13T17:40:51.304] [ERROR] [iPad:210723495] - Error: unsuccessful retcode: -10008
    at parseSso (E:\project\oitq\node_modules\oicq\lib\core\base-client.js:589:15)
    at Bot.packetListener (E:\project\oitq\node_modules\oicq\lib\core\base-client.js:629:27)
    at Network.emit (node:events:394:28)
    at Network.<anonymous> (E:\project\oitq\node_modules\oicq\lib\core\network.js:65:26)
    at Network.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Network.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  args: [ 2 ],
  event: 'internal.verbose'
}
[2022-03-13T17:40:51.304] [ERROR] [iPad:210723495] - Error: unsuccessful retcode: -10008
    at parseSso (E:\project\oitq\node_modules\oicq\lib\core\base-client.js:589:15)
    at Bot.packetListener (E:\project\oitq\node_modules\oicq\lib\core\base-client.js:629:27)
    at Network.emit (node:events:394:28)
    at Network.<anonymous> (E:\project\oitq\node_modules\oicq\lib\core\network.js:65:26)
    at Network.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Network.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  args: [ 2 ],
  event: 'internal.verbose'
}
[2022-03-13T17:40:56.952] [MARK] [iPad:210723495] - 49.7.253.214:8080 closed
[2022-03-13T17:40:57.049] [MARK] [iPad:210723495] - 106.55.128.197:8080 connected
[2022-03-13T17:40:57.136] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:40:57.356] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:40:57.558] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:40:57.750] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:40:57.992] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:40:58.198] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:40:58.468] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:40:58.650] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:40:58.842] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:40:59.075] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:40:59.308] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:40:59.530] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:40:59.754] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:40:59.984] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:41:00.208] [ERROR] [iPad:210723495] - Error: encrypted data is illegal
    at Object.<anonymous> (E:\project\oitq\node_modules\oicq\lib\core\tea.js:103:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ts-node-dev\node_modules\source
-map-support\source-map-support.js:568:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.nodeDevHook [as .js] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ts-node-dev\lib\hoo
k.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (E:\project\oitq\node_modules\oicq\lib\core\network.js:30:26) {
  args: [ 2 ],
  event: 'internal.verbose'
}
[2022-03-13T17:41:00.290] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:41:00.530] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:41:00.814] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:41:01.086] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:41:01.188] [MARK] [iPad:210723495] - 加载了0个好友，0个群，0个陌生人
[2022-03-13T17:41:01.376] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:41:01.638] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:41:01.871] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:41:02.245] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:41:02.497] [MARK] [iPad:210723495] - 登录token过期
[2022-03-13T17:41:02.730] [MARK] [iPad:210723495] - unlocking...
[2022-03-13T17:41:02.946] [MARK] [iPad:210723495] - Welcome, 凉菜 ᴮᴼᵀ ! 正在加载资源...
[2022-03-13T17:41:03.631] [MARK] [iPad:210723495] - 加载了306个好友，2个群，0个陌生人
[2022-03-13T17:41:13.960] [MARK] [iPad:210723495] - 106.55.128.197:8080 closed
[2022-03-13T17:41:14.056] [MARK] [iPad:210723495] - 113.96.18.205:8080 connected
[2022-03-13T17:41:25.962] [MARK] [iPad:210723495] - 113.96.18.205:8080 closed
[2022-03-13T17:41:26.060] [MARK] [iPad:210723495] - 113.96.18.205:8080 connected
[2022-03-13T17:41:37.955] [MARK] [iPad:210723495] - 113.96.18.205:8080 closed
[2022-03-13T17:41:38.047] [MARK] [iPad:210723495] - 113.96.18.205:8080 connected

**Comment by axon-oicq** [comment]
遇到了同样的问题
