### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by xiasongmin1** [takayama-lily/oicq#337]
### Node.js Version

v10.19.0

### Package(oicq) Version

最新

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

请问这个该怎么办呀

### Log Details (控制台日志，请提供包含前后一段时间内的)

  *******************************************************************
  * 欢迎使用 node-onebot
  * 你可以将本程序作为一个无头机器人，或利用本程序进行调试
  * Docs: https://github.com/takayama-lily/oicq/tree/master/http-api
  *******************************************************************

/usr/local/lib/node_modules/oicq/lib/client.js:53
    status = STATUS_OFFLINE;
           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/oicq/lib/oicq.js:9:67)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by takayama-lily** [comment]
升级node
