### ISSUE TITLE
无法发送视频

### ISSUE THREAD

**Issue by misaki-me** [takayama-lily/oicq#464]
### Node.js Version

v14.16.1

### Package(oicq) Version

2.3.1

### Login Protocol

aPad

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

无法发送视频消息，试过绝对路径和相对路径都不行
![QQ截图20221116145230](https://user-images.githubusercontent.com/39290561/202106732-23804caf-9a9c-47c8-b59a-518cf665a995.png)

### Log Details (控制台日志，请提供包含前后一段时间内的)

2022-11-16 14:27:59,366 ERROR 22627 nodejs.unhandledRejectionError: ffmpeg获取视频图像帧失败 at Application._unhandledRejectionHandler (/www/wwwroot/telegram/api/node_modules/egg/lib/egg.js:345:24) at process.emit (events.js:315:20) at processPromiseRejections (internal/process/promises.js:245:33) at processTicksAndRejections (internal/process/task_queues.js:94:32) name: "unhandledRejectionError" pid: 22627 hostname: iZt4n1xusptquzfw28d8trZ

**Comment by misaki-me** [comment]
原来是我没装 ffmpeg

**Comment by mobilelifeful** [comment]
> 没事了，原来是我没装 ffmpeg

 可以发一份 发送图片/视频的 代码吗？

**Comment by misaki-me** [comment]
> > 没事了，原来是我没装 ffmpeg
> 
> 可以发一份 发送图片/视频的 代码吗？

我公开仓库里面有

**Comment by mobilelifeful** [comment]
> > > 没事了，原来是我没装 ffmpeg
> > 
> > 
> > 可以发一份 发送图片/视频的 代码吗？
> 
> 我公开仓库里面有

https://github.com/misaki-me/telegram  是这个吗？ 可以说下
    appID: '', // 申请机器人时获取到的机器人 BotAppID 
    token: '', // 申请机器人时获取到的机器人 BotToken 
    
   在哪里获取吗？ 
   
   直接填写
   
    config.QQaccount = {
     account: "",
     password: ''
   }
   
 来做登陆可以吗？ 🙏

**Comment by mobilelifeful** [comment]
> config.telegram = {
> apiId: " ",
> apiHash: " ",
> token: " : "
> }

那么 config.telegram = {
apiId: " ",
apiHash: " ",
token: " : "
}
这里的token是tg bot吗？
1. 如果是的话， 为什么需要用到bot呢？ 这不是调用TDlib 的吗？
2. 有办法双向 的吗？ 就是QQ的消息 也转到TG？

**Comment by misaki-me** [comment]
1.是tg Bot,为以后拓展其他功能用的，目前没用到
2.文字消息应该可以，媒体消息oicq这边具体有没有提供下载的api，我也不清楚，你可以自己看下
