### ISSUE TITLE
bot.login出错

### ISSUE THREAD

**Issue by AlishaHawkward** [takayama-lily/oicq#78]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string, Buffer, or Uint8Array. Received type number
    at chunkInvalid (_stream_readable.js:329:12)
    at readableAddChunk (_stream_readable.js:261:12)
    at Readable.push (_stream_readable.js:224:10)
    at next (internal/streams/from.js:34:27)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by AlishaHawkward** [comment]
Node版本问题
